Create info and comments controllers
kapatsila-mariia/advertisement_app pull request #23
Opened 2022-01-30 11:03 UTC by kapatsila-mariia

1. Added model and migration for comments;
2. Created controllers for users_info and comments with CRUD operations;
3. Updated models associations;
4. Added method as_json to models;
5. Installed serializer gem;
6. Added serializers for each controller;
7. Updated adverttisements controller;
8. Updated routes

2022-01-31 12:04 UTC, bearded requested changes

2022-01-31 12:04 UTC, bearded commented on app/controllers/comments_controller.rb
> +    elsif current_user.role_id == 2 || @comment.user_id == current_user.id
it is not obvious what does `2` mean, which role it is?
please use sone canonic names or enumerator instead of `role_id == 2`, and wrap it into a method, e.g.:
`current_user.admin?`

2022-01-31 19:47 UTC, kapatsila-mariia commented on app/controllers/comments_controller.rb
> +    elsif current_user.role_id == 2 || @comment.user_id == current_user.id
Added method is_admin.

2022-02-01 12:08 UTC, bearded approved these changes
looks good

2022-02-01 12:12 UTC, merged